# Site settings
email: aps2710@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Tecnoblog - Blog Tecnología de Github
description: Blog de Tecnología de Github - Artículos tecnologicos, programación, smartphone, PC
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Tecnoblog
profile_img: https://s10.postimg.org/61qeeerzd/code.jpg
profile: Tecnoblog
social:
  github: 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
